improve install script

diff --git a/dotfiles b/dotfiles
--- a/dotfiles
+++ b/dotfiles
@@ -49,13 +49,12 @@ function print_help {
   cat << EOF
 Usage: $0 [options]
 
-META OPTIONS 
+META OPTIONS
   --help                     show list of command-line options
 
 BRANCH
   stable                     Use the stable release from GitHub. This will download the latest release as a ZIP file and extract it.
   rolling                    Clone the latest version directly from the GitHub repository. This will use git to clone the repository.
-  
 
 EOF
 }
@@ -85,36 +84,28 @@ done
 
 # _header colorize the given argument with spacing
 function _task {
-  # if _task is called while a task was set, complete the previous
   if [[ $TASK != "" ]]; then
     printf "${OVERWRITE}${LGREEN} [✓]  ${LGREEN}${TASK}\n"
   fi
-  # set new task title and print
   TASK=$1
   printf "${LBLACK} [ ]  ${TASK} \n${LRED}"
 }
 
 # _cmd performs commands with error checking
 function _cmd {
-  # create log if it doesn't exist
   if ! [[ -f $DOTFILES_LOG ]]; then
     touch $DOTFILES_LOG
   fi
-  # empty conduro.log
   > $DOTFILES_LOG
-  # hide stdout, on error we print and exit
   if eval "$1" 1> /dev/null 2> $DOTFILES_LOG; then
     return 0 # success
   fi
-  # read error from log and add spacing
   printf "${OVERWRITE}${LRED} [X]  ${TASK}${LRED}\n"
   while read line; do
     printf "      ${line}\n"
   done < $DOTFILES_LOG
   printf "\n"
-  # remove log file
   rm $DOTFILES_LOG
-  # exit installation
   exit 1
 }
 
@@ -127,13 +118,29 @@ function _task_done {
   _clear_task
 }
 
-function arch_setup() {
+function backup_dotfiles() {
+  local backup_dir="$HOME/dotfiles_backup/$(date +'%Y%m%d_%H%M%S')"
+  _task "Creating backup directory: $backup_dir"
+  mkdir -p "$backup_dir" || {
+    printf "${LYELLOW} [-] Failed to create backup directory. Skipping backup.\n"
+    return 1
+  }
+
+  _task "Backing up dotfiles"
+  if mv "$DOTFILES_DIR/"* "$backup_dir/" 2>/dev/null; then
+    _task_done
+  else
+    printf "${LYELLOW} [-] Couldn't find files to back up. Skipping.\n"
+  fi
+}
+
+# Arch setup function
+function arch_setup {
   if ! [ -x "$(command -v ansible)" ]; then
     _task "Installing Ansible"
     _cmd "sudo pacman -Sy --noconfirm"
     _cmd "sudo pacman -S --noconfirm ansible"
     _cmd "sudo pacman -S --noconfirm python-argcomplete"
-    # _cmd "sudo activate-global-python-argcomplete3"
   fi
   if ! pacman -Q python3 >/dev/null 2>&1; then
     _task "Installing Python3"
@@ -152,7 +159,7 @@ function arch_setup() {
     _cmd "sudo pacman -S --noconfirm openssh"
   fi
   if ! pacman -Q rsync >/dev/null 2>&1; then
-    _task "Installing Unzip"
+    _task "Installing Rsync"
     _cmd "sudo pacman -S --noconfirm rsync"
   fi
   if ! pacman -Q git >/dev/null 2>&1; then
@@ -161,7 +168,8 @@ function arch_setup() {
   fi
 }
 
-update_ansible_galaxy() {
+# Function to update Ansible Galaxy
+function update_ansible_galaxy() {
   local os=$1
   local os_requirements=""
   _task "Updating Ansible Galaxy"
@@ -195,8 +203,8 @@ download_latest_release() {
   local zip_url=$(get_latest_zip)
   local zip_file="$HOME/dotfiles_latest.zip"
 
-  _task "Deleting existing dotfiles directory contents"
-  _cmd "rm -rf $DOTFILES_DIR/*"
+  _task "Backing up existing dotfiles"
+  backup_dotfiles
 
   _task "Downloading the latest release from GitHub"
   _cmd "curl -L -o $zip_file $zip_url"
@@ -229,39 +237,6 @@ case $ID in
     _cmd "echo 'Unsupported OS'"
     ;;
 esac
-
-# Backup dotfiles
-backup_dotfiles() {
-  local backup_dir="$HOME/dotfiles_backup/$(date +'%Y%m%d_%H%M%S')"
-  _task "Creating backup directory: $backup_dir"
-  if mkdir -p "$backup_dir"; then
-    _task_done
-  else
-    printf "${LYELLOW} [-] Failed to create backup directory. Skipping backup.\n"
-    return 1
-  fi
-
-  _task "Backing up .config directory"
-  if cp -r "$HOME/.config" "$backup_dir" 2>/dev/null; then
-    _task_done
-  else
-    printf "${LYELLOW} [-] Couldn't find .config to create a back up directory. Skipping.\n"
-  fi
-
-  _task "Backing up .zshrc"
-  if cp "$HOME/.zshrc" "$backup_dir" 2>/dev/null; then
-    _task_done
-  else
-    printf "${LYELLOW} [-] Couldn't find .zshrc to create a backup. Skipping.\n"
-  fi
-
-  _task "Backing up .bashrc"
-  if cp "$HOME/.bashrc" "$backup_dir" 2>/dev/null; then
-    _task_done
-  else
-    printf "${LYELLOW} [-] Couldn't find .bashrc to create a backup. Skipping.\n"
-  fi
-}
 
 backup_dotfiles
 
