Maintenance fixups as per your request :3 (#45)
* Kinda rewrite the README

Lots of grammar and markdown improvements.

The inconsistency of markdown+HTML amalgamation should still be addressed.

* Add more details about the repo

As per the request upstream.

* Fix the address parsing and simplify some of the logic using GitHub CLI

* Improve the release logic

The previous logic used to depend on the VERSION file being pushed,
which causes a new release to fail to be generated if the new release
was deleted.

* Fix the removal of the URL and the divider after that

---------

Co-authored-by: Bahar Kurt <kurtbahartr@users.noreply.github.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -2,29 +2,50 @@ name: Create Release on Version Update
 
 on:
   push:
-    paths:
-      - VERSION
+    branches:
+      - 'main'
 
 jobs:
   create-release:
     runs-on: ubuntu-latest
+    continue-on-error: true
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Compare current release with VERSION file
+        id: compare_versions
+        run: |
+          if [ "$(gh release view -q '.tagName' --json tagName)" == "$(cat VERSION)" ]; then
+            echo "No new release to generate!"
+            echo "NEW_RELEASE=0" >> $GITHUB_ENV
+            exit
+          fi
+          # Apparently the tag still exists when the release is deleted from GitHub web interface...
+          # Also mock the exit status so that it always returns with code 0.
+          git push --delete origin refs/tags/$(cat VERSION) || true
+          echo "NEW_RELEASE=1" >> $GITHUB_ENV
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Run catalog script
         id: run_script
+        if: ${{ env.NEW_RELEASE == '1' }}
         run: |
           # Execute the script and save the output
-          if [ -x scripts/GetCatalog.md ]; then
-            ./scripts/GetCatalog.md > release_notes.md
+          if [ -x scripts/GetCatalog.sh ]; then
+            GH_TOKEN=$GH_TOKEN ./scripts/GetCatalog.sh > release_notes.md
           else
-            echo "scripts/GetCatalog.md is not executable or not found"
+            echo "scripts/GetCatalog.sh is not executable or not found"
             exit 1
           fi
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Create tag
         id: create_tag
+        if: ${{ env.NEW_RELEASE == '1' }}
         run: |
           # Generate a new tag based on the version
           TAG_NAME=$(cat VERSION)
@@ -34,12 +55,14 @@ jobs:
 
       - name: Output release notes
         id: output_release_notes
+        if: ${{ env.NEW_RELEASE == '1' }}
         run: |
           echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
           cat release_notes.md >> $GITHUB_ENV
           echo "EOF" >> $GITHUB_ENV
 
       - name: Create release
+        if: ${{ env.NEW_RELEASE == '1' }}
         uses: actions/create-release@v1
         with:
           tag_name: ${{ env.TAG_NAME }}
@@ -49,3 +72,4 @@ jobs:
           prerelease: false
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
